Attempt to get pipewire logs after test execution.

diff --git a/.github/workflows/cmake-linux.yml b/.github/workflows/cmake-linux.yml
--- a/.github/workflows/cmake-linux.yml
+++ b/.github/workflows/cmake-linux.yml
@@ -59,6 +59,7 @@ jobs:
       run: |
           sudo systemctl enable rtkit-daemon
           sudo systemctl start rtkit-daemon
+          systemctl --user enable wireplumber pipewire pipewire-pulse
           Xvfb :99 -screen 0 1024x768x16 &
           sleep 5
           export DISPLAY=:99.0
@@ -67,11 +68,10 @@ jobs:
           chmod 700 $XDG_RUNTIME_DIR
           eval "$(dbus-launch --sh-syntax --exit-with-x11)"
           metacity --sm-disable --replace &
-          systemctl --user start wireplumber pipewire pipewire-pulse
           sleep 5
-          journalctl -xe | grep pipewire
-          journalctl -xe | grep wireplumber
           ln -s ${{github.workspace}}/build_linux/rade_src/model19_check3 model19_check3
           . ../rade-venv/bin/activate
-          PYTHONPATH=${{github.workspace}}/build_linux/rade_src:$PYTHONPATH ctest -V
+          PYTHONPATH=${{github.workspace}}/build_linux/rade_src:$PYTHONPATH ctest -V || echo "failed"
+          journalctl -xe | grep pipewire
+          journalctl -xe | grep wireplumber
       
